export const EmailObject = [
    {
        sender: "Linda from SparkleClean",
        header: "Your Home Deserves Better",
        intro: "We noticed your home hasn’t been professionally cleaned in a while… based on absolutely no data.",
        body: "Hi there! We thought you might enjoy a friendly nudge to book a cleaning service. Our team will sweep, scrub, and sparkle every corner—whether you asked us to or not. Book today and we’ll throw in a complimentary air freshener shaped like a pineapple.",
        dateSent: "2025-09-01",
        emailOpened: false,
        importance: "medium",
        type: "personal",
        imgUrl: "../src/assets/react.svg",
        id: 1,
        isCurrent: false,
    },
    {
        sender: "TechNova Updates",
        header: "Important Security Patch Available",
        intro: "We’ve released a critical update that fixes a bug we introduced last week.",
        body: "Dear user, this patch will prevent your devices from developing a mind of their own. It’s quick, painless, and only slightly suspicious. Install now to keep your toaster from joining a rogue AI uprising.",
        dateSent: "2025-09-02",
        emailOpened: false,
        importance: "high",
        type: "work",
        imgUrl: "../src/assets/react.svg",
        id: 2,
        isCurrent: false,
    },
    {
        sender: "Greg from FitFuel",
        header: "Your Free Trial Is Ending!",
        intro: "Just a friendly reminder that your free trial ends tomorrow.",
        body: "Hey champ! We’ll start charging you for premium protein powder you never ordered unless you cancel. But why cancel when you could have a lifetime supply of chalk-flavored shakes delivered to your door?",
        dateSent: "2025-09-03",
        emailOpened: false,
        importance: "medium",
        type: "personal",
        imgUrl: "../src/assets/react.svg",
        id: 3,
        isCurrent: false,
    },
    {
        sender: "The Daily Bark",
        header: "Top 10 Dog Breeds That Secretly Judge You",
        intro: "You won’t believe what your dog is thinking when you wear socks with sandals.",
        body: "Hello fellow canine enthusiast! From the aloof Afghan Hound to the side-eyeing Shiba Inu, we’ve compiled a list of breeds that silently critique your life choices. Click now for judgmental fluff and wagging tails.",
        dateSent: "2025-09-04",
        emailOpened: false,
        importance: "low",
        type: "personal",
        imgUrl: "../src/assets/react.svg",
        id: 4,
        isCurrent: false,
    },
    {
        sender: "Nina from ZenBank",
        header: "Your Account Needs Attention",
        intro: "We noticed some unusual activity on your account… like you actually saving money.",
        body: "Hi Ella, we just wanted to check in and make sure everything is okay. Also, while you’re here, why not explore our new ‘Impulse Buy’ credit card? Perfect for undoing all that responsible saving.",
        dateSent: "2025-09-05",
        emailOpened: false,
        importance: "high",
        type: "work",
        imgUrl: "../src/assets/react.svg",
        id: 5,
        isCurrent: false,
    },
    {
        sender: "PixelPop Games",
        header: "Your Kingdom Is Under Attack!",
        intro: "Your virtual village is being pillaged while you ignore our notifications.",
        body: "Greetings, noble ruler! The goblins are at your gates, the villagers are panicking, and your crops are wilting. Log in now to save your kingdom—or let it all burn and start fresh next season.",
        dateSent: "2025-09-06",
        emailOpened: false,
        importance: "medium",
        type: "personal",
        imgUrl: "../src/assets/react.svg",
        id: 6,
        isCurrent: false,
    },
    {
        sender: "Dr. Wellness",
        header: "You Haven’t Logged Your Water Intake Today",
        intro: "Your hydration streak is in danger.",
        body: "Hi Ella, we’re not saying you’ll shrivel up, but your plants are starting to look healthier than you. Log your water now and earn a shiny digital badge that means absolutely nothing in real life.",
        dateSent: "2025-09-07",
        emailOpened: false,
        importance: "low",
        type: "personal",
        imgUrl: "../src/assets/react.svg",
        id: 7,
        isCurrent: false,
    },
    {
        sender: "BargainBlast",
        header: "Ella, You Left Something in Your Cart!",
        intro: "That neon llama lamp you almost bought is still waiting.",
        body: "Hey there! It’s been three days and your llama lamp is feeling abandoned. Come back and complete your purchase before it finds a new home—or worse, goes on clearance without you.",
        dateSent: "2025-09-08",
        emailOpened: false,
        importance: "medium",
        type: "personal",
        imgUrl: "../src/assets/react.svg",
        id: 8,
        isCurrent: false,
    },
    {
        sender: "CodeCrafters Weekly",
        header: "Top 5 Java Mistakes You’re Definitely Making",
        intro: "We know you’re a coding wizard, but here’s a list of things you probably messed up anyway.",
        body: "Hi Ella, from forgetting to close streams to overcomplicating loops, we’ve compiled the most common Java blunders. Read on, learn something new, and maybe feel a little smug when you realize you’ve avoided them.",
        dateSent: "2025-09-08",
        emailOpened: false,
        importance: "high",
        type: "work",
        imgUrl: "../src/assets/react.svg",
        id: 9,
        isCurrent: false,
    },
    {
        sender: "MysteryBox Monthly",
        header: "Your Subscription Is Almost Here!",
        intro: "Your box of vaguely useful trinkets is en route.",
        body: "Hello adventurer! Prepare for a curated selection of items you didn’t know you needed—until now. Will it be a glow-in-the-dark spoon? A miniature cactus? The suspense is half the fun.",
        dateSent: "2025-09-08",
        emailOpened: false,
        importance: "low",
        type: "personal",
        imgUrl: "../src/assets/react.svg",
        id: 10,
        isCurrent: false,
    },
];
