export const EmailData = [
    {
        sender: "Linda from SparkleClean",
        header: "Your Home Deserves Better",
        body: "Hi there! We noticed your home hasn't been professionally cleaned in a while... based on absolutely no data. Let us guilt you into booking a service!",
        dateSent: "2025-09-01",
        emailOpened: false,
        imgUrl: "./src/assets/react.svg",
    },
    {
        sender: "TechNova Updates",
        header: "Important Security Patch Available",
        body: "Dear user, we've released a critical update that fixes a bug we introduced last week. Please install it before your toaster becomes self-aware.",
        dateSent: "2025-09-02",
        emailOpened: false,
        imgUrl: "./src/assets/react.svg",
    },
    {
        sender: "Greg from FitFuel",
        header: "Your Free Trial Is Ending!",
        body: "Hey champ! Just a friendly reminder that your free trial ends tomorrow, and we’ll start charging you for protein powder you never ordered.",
        dateSent: "2025-09-03",
        emailOpened: false,
        imgUrl: "./src/assets/react.svg",
    },
    {
        sender: "The Daily Bark",
        header: "Top 10 Dog Breeds That Secretly Judge You",
        body: "Hello fellow canine enthusiast! You won’t believe what your dog is thinking when you wear socks with sandals. Click now for judgmental fluff!",
        dateSent: "2025-09-04",
        emailOpened: false,
        imgUrl: "./src/assets/react.svg",
    },
    {
        sender: "Nina from ZenBank",
        header: "Your Account Needs Attention",
        body: "Hi Ella, we noticed some unusual activity on your account... like you actually saving money. Just kidding, we just want you to open our app.",
        dateSent: "2025-09-05",
        emailOpened: false,
        imgUrl: "./src/assets/react.svg",
    },
    {
        sender: "PixelPop Games",
        header: "Your Kingdom Is Under Attack!",
        body: "Greetings, noble ruler! Your virtual village is being pillaged while you ignore our notifications. Return now or face pixelated doom!",
        dateSent: "2025-09-06",
        emailOpened: false,
    },
    {
        sender: "Dr. Wellness",
        header: "You Haven’t Logged Your Water Intake Today",
        body: "Hi Ella, your hydration streak is in danger. We’re not saying you’ll shrivel up, but your plants are starting to look healthier than you.",
        dateSent: "2025-09-07",
        emailOpened: false,
    },
    {
        sender: "BargainBlast",
        header: "Ella, You Left Something in Your Cart!",
        body: "Hey there! That neon llama lamp you almost bought is still waiting. It’s emotionally fragile and needs closure. Come back and complete your purchase.",
        dateSent: "2025-09-08",
        emailOpened: false,
    },
    {
        sender: "CodeCrafters Weekly",
        header: "Top 5 Java Mistakes You’re Definitely Making",
        body: "Hi Ella, we know you’re a coding wizard, but here’s a list of things you probably messed up anyway. Read on and feel mildly attacked.",
        dateSent: "2025-09-08",
        emailOpened: false,
    },
    {
        sender: "MysteryBox Monthly",
        header: "Your Subscription Is Almost Here!",
        body: "Hello adventurer! Your box of vaguely useful trinkets is en route. Prepare to be underwhelmed and delighted at the same time.",
        dateSent: "2025-09-08",
        emailOpened: false,
    },
];
